ALTER TABLE "Anime" ADD COLUMN "favorite" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Anime" ADD COLUMN "status" TEXT NOT NULL DEFAULT 'COMPLETED';
ALTER TABLE "Anime" ALTER COLUMN "status" SET DEFAULT 'PLANNED';
